spring:
  application:
    name: identity-service

  datasource:
    # for Local-to-Docker Communication (local identity_service to container postgres)
    url: ${DBMS_CONNECTION:jdbc:postgresql://localhost:5432/identity_service}

    # for Docker-to-Docker Communication (container identity_service to container postgres + with same network)
    # url: ${DBMS_CONNECTION:jdbc:postgresql://postgres:5432/identity_service}
    username: postgres
    password: 1234
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    properties:
      hibernate:
        format_sql: true

server:
  port: 8080

jwt:
  signerKey: "feoqgwuvjddf1u2reureloqrq3h951gw"
  valid-duration: 60 # in seconds
  refreshable-duration: 300 # in seconds

management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      show-details: always
