spring:
  application:
    name: identity-service

  datasource:
    url: jdbc:postgresql://localhost:5432/identity_service
    username: postgres
    password: 1234
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    properties:
      hibernate:
        format_sql: true

server:
  port: 8080


jwt:
  signerKey: "feoqgwuvjddf1u2reureloqrq3h951gw"
  valid-duration: 10 # in seconds
  refreshable-duration: 15 # in seconds